# Generated by Django 3.2.6 on 2023-01-14 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0004_auto_20230114_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('personal_id', models.CharField(max_length=11, verbose_name='ID')),
                ('current_address', models.CharField(max_length=200, verbose_name='Current Address')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('sex', models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=3, verbose_name='Sex')),
                ('employee_type', models.CharField(choices=[('developers', 'Developer'), ('others', 'Others')], max_length=140, verbose_name='Type')),
                ('candidate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.candidate', verbose_name='Candidate')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
