# Generated by Django 3.2.6 on 2023-01-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('personal_id', models.CharField(max_length=11, verbose_name='ID')),
                ('current_address', models.CharField(max_length=200, verbose_name='Current Address')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('sex', models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=3, verbose_name='Sex')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('candidates', models.ManyToManyField(to='campaigns.Candidate', verbose_name='Candidates')),
            ],
        ),
    ]
