# Generated by Django 3.2.6 on 2023-01-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20230113_2255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='technologyexperience',
            unique_together={('technology', 'candidate')},
        ),
    ]
