# Generated by Django 3.2.6 on 2023-01-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_technologyexperience_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologyexperience',
            options={'ordering': ('-years_xp',), 'verbose_name': 'Technology Experience', 'verbose_name_plural': 'Technologies Experience'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personal_id',
            field=models.CharField(max_length=11, unique=True, verbose_name='ID'),
        ),
    ]
